# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Limfjordssekretariatet_tools
                                 A QGIS plugin
 Limfjordssekretariatet forskellige tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-05
        copyright            : (C) 2025 by Henrik Rosenskjold, Limfjordssekretariatet
        email                : henrik.rosenskjold@aalborg.dk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Limfjordssekretariatet_tools class from file Limfjordssekretariatet_tools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Limf_tools import Limfjordssekretariatet_tools
    return Limfjordssekretariatet_tools(iface)
